language: cpp

compiler: g++-4.9

dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - g++-4.9
      - cmake
      - cmake-data
      - xorg-dev
      - libglu1-mesa-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./GibTest