language: cpp
compiler: g++
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test   # gcc-8
    packages:
      - g++-8
      - gcc-8
      - xorg-dev
      - libglu1-mesa-dev
      - libgtk-3-dev

install:
  - sudo ./travis-install.sh

script:
  - mkdir build
  - cd build
  - cmake .. -DBUILD_TESTS=ON -DBUILD_EDITOR=OFF -DCMAKE_TOOLCHAIN_FILE=/home/travis/vcpkg/scripts/buildsystems/vcpkg.cmake
  - make
  - ./Tests/GibTest