# Specify version format
version: "1.0.{build}"

# Operating system (build VM template)
os: Visual Studio 2017

# build platform, i.e. Win32 (instead of x86), x64, Any CPU. This setting is optional.
platform: 
  - Win32
  - x64

# specify custom environment variables
environment:
  MSVC_DEFAULT_OPTIONS: ON
  GIBENGINE_VCPKG_EXPORT_URL: http://s3.gibengine.xyz/gibengine-ci/vcpkg
  GIBENGINE_VCPKG_NAME: gibengine-vcpkg
  GIBENGINE_VCPKG_FILE: gibengine-vcpkg.7z

# build configuration, i.e. Debug, Release, etc.
configuration:
  - Debug

# branches to build
branches:
  except:
    - gh-pages

# scripts to run before build
before_build:
  - ps: If ($env:PLATFORM -eq "Win32") { $env:VCPKG_TARGET_TRIPLET="x86-windows" }
  - ps: If($env:PLATFORM -eq "x64") { $env:VCPKG_TARGET_TRIPLET="x64-windows" }
  - ps: appveyor DownloadFile "$env:GIBENGINE_VCPKG_EXPORT_URL/$env:VCPKG_TARGET_TRIPLET/$env:GIBENGINE_VCPKG_FILE" -FileName "${env:GIBENGINE_VCPKG_FILE}" -Timeout 600000
  - ps: 7z x ${env:GIBENGINE_VCPKG_FILE} -oc:\
  - cmd: cd c:\projects\gibengine
  - cmd: md build
  - cmd: cd build
  - cmd: if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 15 2017
  - cmd: if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 15 2017 Win64
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -DVCPKG_TARGET_TRIPLET=%VCPKG_TARGET_TRIPLET% -DCMAKE_TOOLCHAIN_FILE=c:\%GIBENGINE_VCPKG_NAME%\scripts\buildsystems\vcpkg.cmake -DCMAKE_BUILD_TYPE=%configuration%  -DBUILD_EDITOR=OFF -DBUILD_TESTS=ON  ..

build:
  project: c:\projects\gibengine\build\GibEngine.sln
  parallel: true

test_script:
  - cmd: cd C:\projects\gibengine\build\Tests\Debug
  - cmd: GibTest.exe --gtest_output=xml:test_gibengine.xml

on_finish:
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test_gibengine.xml))
